theme: jekyll-theme-cayman

title: FOSD 2018 Meeting
subtitle: June 3-6, 2018, Gothenburg
description: Welcome to the Web site of the Feature Oriented Software Development Meeting (FOSD) 2018

header_image: header.jpg

repository: FOSD/FOSD2018
url: https://fosd.github.io
baseurl: /FOSD2018

defaults:
  - scope:
      path: "pages"
    values:
      permalink: :basename

exclude: [CNAME, Gemfile, Gemfile.lock, README.md]
